version: '3'
services:
  py-srv:
    build: py-srv
    ports:
      - "80:8000"
    depends_on:
      - db-runner
    links:
      - "db:db"
      
  py-test-srv:
    build:
      context: py-test-srv
    command: sh -c "/wait && python app.py"
    environment:
      - WAIT_HOSTS=py-srv:8000
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - py-srv
    links:
      - "py-srv:py-srv"

  db:
    image: cockroachdb/cockroach:v19.2.4
    container_name: db
    ports:
     - "20000:26257"
     - "8000:8080"
    command: start --insecure

  db-runner:
    image: cockroachdb/cockroach:v19.2.4
    command:
      - shell
      - /usr/local/bin/init-data.sh
      - db:26257
    volumes:
     - ./db/init-data.sh:/usr/local/bin/init-data.sh:ro
     - ./db/sql:/docker-entrypoint-initdb.d
    depends_on:
     - db
    links:
     - "db:db"
